baseURL = 'https://prohairesis.xyz/'
languageCode = 'en-us'
title = 'Prohairesis'
theme = 'typo'

# Disable tags, actually, they are rendered as a list, but the idea is to disable them.
disableKinds = ['taxonomy']

# Google analytics code
googleAnalytics = "G-xxxxxxxxxx"

[params]
# Math mode
math = true

# Intro on main page, content in markdown, if you omit title or content the other can be displayed
homeIntro = true
homeIntroTitle = 'Hi'
homeIntroContent = """
Join me on this journey as I explore ideas and how to apply them
"""

# Collection to display on home page: 
# in this case we would display content/posts pages
homeCollectionTitle = 'Posts'
homeCollection = 'posts'

# Pagination size across all website, this is the same for homepage and single list page
paginationSize = 100

# Social icons
# [[params.social]]
# name = "linkedin"
# url = "https://www.linkedin.com/in/your-name"

# [[params.social]]
# name = "medium"
# url = "https://medium.com/@your-name"

# [[params.social]]
# name = "github"
# url = "https://github.com/your-name"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"


# Syntax highligth on code blocks, all styles: 
# https://xyproto.github.io/splash/docs/all.html
# I suggest algol
[markup]
[markup.highlight]
style = 'algol'